workspace:
  base: /go
  path: src/loe.yt/drone-mailjet

pipeline:

  build:
    image: golang:1.8
    environment:
      - CGO_ENABLED=0
    commands:
      - go build -ldflags='-X "main.Version=${DRONE_TAG=dev}+${DRONE_COMMIT_SHA:0:7}"' -tags netgo

  publish-latest:
    image: plugins/docker
    repo: loeyt/drone-mailjet
    tags: 
      - latest
    when:
      branch: master
      event: push

  # This is protection for the publish-tag step. If this starts to fail,
  # update both test-tag and publish-tag steps.
  test-tag:
    image: alpine:3.5
    commands:
      - test ${DRONE_TAG} = 0.1.${DRONE_TAG##0.1.}
    when:
      event: tag

  publish-tag:
    image: plugins/docker
    repo: loeyt/drone-mailjet
    tags: 
      - ${DRONE_TAG}
      - 0.1
    when:
      event: tag

  notify:
    image: loeyt/drone-mailjet:latest
    fromname: loe.yt Drone CI
    fromemail: drone@loe.yt
    recipientname: Luit van Drongelen
    recipientemail: luitvd@gmail.com
    template: 113576
    subject: "[${DRONE_REPO_NAME}] build ${DRONE_BUILD_STATUS}"
    when:
      status:
        - success
        - failure
